(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ca=ba(this),da=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var e=0;e<
a.length-1;e++){var f=a[e];if(!(f in c))break a;c=c[f]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}};da("Array.from",function(a){return a?a:function(b,c,e){c=null!=c?c:function(ea){return ea};var f=[],l="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof l){b=l.call(b);for(var m=0;!(l=b.next()).done;)f.push(c.call(e,l.value,m++))}else for(l=b.length,m=0;m<l;m++)f.push(c.call(e,b[m],m));return f}});
var d=this||self,fa=/^[\w+/_-]+[=]{0,2}$/,g=null,h=function(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&fa.test(a)?a:""},k=function(a){return a};var ha=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,e="string"===typeof a?a.split(""):a,f=0;f<c;f++)if(f in e&&b.call(void 0,e[f],f,a))return!0;return!1};var n;var q=function(a,b){this.c=b===p?a:""},p={};var r;a:{var t=d.navigator;if(t){var u=t.userAgent;if(u){r=u;break a}}r=""};var v=function(a){if(void 0===n){var b=null;var c=d.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:k,createScript:k,createScriptURL:k})}catch(e){d.console&&d.console.error(e.message)}n=b}else n=b}a=(b=n)?b.createScriptURL(a):a;return new q(a,p)};var w=function(a,b){if(!ia()){var c=Math.random();if(c<b)return c=ja(),a[Math.floor(c*a.length)]}return null},ja=function(){if(!d.crypto)return Math.random();try{var a=new Uint32Array(1);d.crypto.getRandomValues(a);return a[0]/65536/65536}catch(b){return Math.random()}},ia=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){return ha(["Google Web Preview","Mediapartners-Google","Google-Read-Aloud","Google-Adwords"],ka)||1E-4>Math.random()}),ka=function(a){return-1!=r.indexOf(a)};var la=function(a,b){b=void 0===b?!0:b;try{for(var c=null;c!=a;c=a,a=a.parent)switch(a.location.protocol){case "https:":return!0;case "file:":return b;case "http:":return!1}}catch(e){}return!0}(d,!1)?"https:":"http:";var x={i:1,g:4,h:5,f:7},y={b:"40004006",a:"40004007"};function ma(){return{1:.5,4:.02,5:.001,7:.05}}function na(){var a=z,b=typeof a;if(("object"!=b||null==a)&&"function"!=b)return!1;for(var c in x)if(b=a[x[c]],"number"!==typeof b||0>b||1<b)return!1;return!0};function oa(){var a=d.dcmads;if(null!=a.eids)return a.eids;var b=d.navigator;return b.connection&&b.connection.saveData?(a=w([y.b,y.a],a.expts[4]))?"4|"+a:"":""};try{d.dcmads=d.dcmads||{};d.dcmads.startTime=(new Date).getTime();var pa=d.dcmads,A=d.dcmads.version,B={loader:168};if(A)if(B.experiment=A.experiment,61==A.number||"p"==A.number)B.number=61;else if(61==A.number||"c"==A.number)B.number=61;if(!B.number){var C=w([61,61],0);B.experiment=!!C;B.number=C||61}pa.version=B;var qa=d.dcmads,D,z=d.dcmads.expts,E;E=void 0===E?ma:E;D=na()?z:E();qa.expts=D;d.dcmads.eids=oa();var ra="4|"+y.a,F,G=d.dcmads.version,H=G.number,I="";G.experiment&&61==H&&(I="?rxp=61x61");
var sa="impl_v"+H+".js"+I,J=d.document,K=J.currentScript||Array.from(J.getElementsByTagName("script")).pop();F=(0==(K&&K.src||"").indexOf("http:")?"http:":"https:")+"//www.googletagservices.com/dcm/"+sa;if(d.dcmads.eids===ra){var L=d.document,M=v(F),N=L.createElement("script"),O="string"===typeof M?v(M):M;N.src=O instanceof q&&O.constructor===q?O.c:"type_error:TrustedResourceUrl";var P;var Q=N.ownerDocument&&N.ownerDocument.defaultView;Q&&Q!=d?P=h(Q.document):(null===g&&(g=h(d.document)),P=g);P&&
N.setAttribute("nonce",P);var R=L.getElementsByTagName("script")[0];R&&R.parentNode&&R.parentNode.insertBefore(N,R)}else d.document.write('<script src="'+F+'">\x3c/script>')}catch(a){if(.01>Math.random()){var S="";try{var T,U=a.toString();a.name&&-1==U.indexOf(a.name)&&(U+=": "+a.name);a.message&&-1==U.indexOf(a.message)&&(U+=": "+a.message);if(a.stack){var V=a.stack,W=U;try{-1==V.indexOf(W)&&(V=W+"\n"+V);for(var X;V!=X;)X=V,V=V.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");U=V.replace(/\n */g,
"\n")}catch(b){U=W}}T=U;T=T.substring(0,1024);S=encodeURIComponent(T)}catch(b){S="extr"}var Y=d.dcmads.eids,Z=document.createElement("img");Z.src=la+"//pagead2.googlesyndication.com/pagead/gen_204?id=dcmads-err&ver=168&context=554"+((Y?"&eids="+Y:"")+"&msg="+S);(d.google_image_requests=d.google_image_requests||[]).push(Z)}};}).call(this);
